#!/bin/sh

# Set these paths appropriately

BIN="/home/yassine/Desktop/lemma/bin"
CMD="/home/yassine/Desktop/lemma/cmd"
LIB="/home/yassine/Desktop/lemma/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/russian.par

# do tokenization
$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
