#!/bin/sh

# Set these paths appropriately

BIN="/home/yassine/Desktop/lemma/bin"
CMD="/home/yassine/Desktop/lemma/cmd"
LIB="/home/yassine/Desktop/lemma/lib"

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/catalan-abbreviations
PARFILE=${LIB}/catalan.par

$TOKENIZER -c -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
