#!/bin/sh

# Set these paths appropriately

BIN="/home/yassine/Desktop/lemma/bin"
CMD="/home/yassine/Desktop/lemma/cmd"
LIB="/home/yassine/Desktop/lemma/lib"

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovenian.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
